module ErrorCode 
  ( decode
  , encode
  ) where

data ErrorCode
  = UnknownServerError
  | None
  | OffsetOutOfRange
  | CorruptMessage
  | UnknownTopicOrPartition
  | InvalidFetchSize
  | LeaderNotAvailable
  | NotLeaderForPartition
  | RequestTimedOut
  | BrokerNotAvailable
  | ReplicaNotAvailable
  | MessageTooLarge
  | StaleControllerEpoch
  | OffsetMetadataTooLarge
  | NetworkException
  | CoordinatorLoadInProgress
  | CoordinatorNotAvailable
  | NotCoordinator
  | InvalidTopicException
  | RecordListTooLarge
  | NotEnoughReplicas
  | NotEnoughReplicasAfterAppend
  | InvalidRequiredAcks
  | IllegalGeneration
  | InconsistentGroupProtocol
